config/routes.rb
Rails.application.routes.draw do
  resources :apartments

  root 'apartments#index'
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :apartments

    def to_s 
        self.name
    end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
    def index
        @apartments = Apartment.all
    end

    def new
        @apartment = Apartment.new
        @building = Building.new
        @building = Building.pluck(:name, :id)
    end

    def show
        @apartment = Apartment.find(params[:id])
    end

    def create
        @apartment = Apartment.new(apartment_params)
        
        respond_to do |format| 
            if @apartment.save
                format.html { redirect_to @apartment, notice: 'Apartment was successfully created.'}
            else
                format.html { render :new }
            end
        end
    end

    private

    def apartment_params
        params.require(:apartment).permit(:number, :building_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true) do |form| %> 
    <% if apartment.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(apartment.errors.count, "error") %> prohibited
    this apartment from being saved:</h2>
        <ul>
        <% apartment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    
    <div class="field">
        <%= form.label :number %>
        <%= form.text_field :number %>
    </div>
    <div class="field">
        <%= form.label :building_id %>
        <%= form.select :building_id, @buidings %>
    </div>
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/apartments/index.html.erb
<h1>Apartments</h1>
 <table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
 <% @apartments.each do |apartment| %>
  <tr>
   <td><%= apartment.number %></td>
   <td><%= apartment.building%></td>
   <td><%= link_to 'Show', apartment %></td>
 </tr>
 <% end %>
</tbody>
</table>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1> New Apartment </h1>

<%= render 'form', apartment: @apartment, building: @building %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p>
    <strong>Number:</strong>
    <%= @apartment.number %>
</p>

<p>
    <strong>Building:</strong>
    <%= @apartment.building %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EjeRelacionesUnoAN</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>